### ISSUE TITLE
Missing named-release tags

### ISSUE THREAD

**Issue by mtyaka** [edx/edx-notes-api#48]
At OpenCraft we've been using `named-release/*` tags for automatic instance deployments: https://github.com/open-craft/opencraft/blob/7b4be3aa6b89c4111881b66d118d076c3be3557f/instance/templates/instance/ansible/vars.yml#L72

The `edx-notes-api` app gets deployed by `edx_sandbox.yml` playbook and we would like to manage it in the same way (ie. set `EDX_NOTES_API_VERSION` to `"named-release/dogwood.3"` or similar).

Would it be possible to add some git tags to this repository, at least for dogwood? The commit that we normally use with dogwood is 05dba592531538ed113a86871161fced4fcf7fed.

For more info see discussion at https://github.com/open-craft/opencraft/pull/109

**Comment by bradenmacdonald** [comment]
@mtyaka I don't think this is necessary, at least for Dogwood. This was an oversight in the Dogwood release, but was fixed by @nedbat who simply removed edx-notes-api from the default install with PR https://github.com/edx/configuration/pull/2861 . We can do the same since none of our instances need edx-notes.

**Comment by mtyaka** [comment]
@bradenmacdonald You're right, we can remove edx-notes-api from our instances. I'm closing this issue.
